### ISSUE TITLE
Add README with build instructions?

### ISSUE THREAD

**Issue by hemberger** [smrealms/TheLazyTrader#2]
It occurs to me that I have no idea how to build this project to support future changes to the `.smr` file format. Would it be possible to add a README with instructions for how to build it? Any amount of help would be greatly appreciated!

**Comment by Page-** [comment]
I think if you open it with netbeans then it should mostly "just work" @hemberger, I'll need to find some time to set it up in vscode and/or docker at some point to hopefully make it more straightforward

**Comment by hemberger** [comment]
I would be delighted if we could do this via docker. Even if you only have time to give me a rough idea of what command to run, I'd be happy to start hacking away at a Dockerfile. It's been well over a decade since I used an IDE, and the install for netbeans is huge (200 packages and 1GB of disk space), so I'm reluctant to go that route if I don't need to. :)

**Comment by XaeroDegreaz** [comment]
#4 Might help
